package com.redhat.rhdm.demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Article implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Article ID")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("Description")
	private java.lang.String description;

	public Article() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public Article(java.lang.String id, java.lang.String description) {
		this.id = id;
		this.description = description;
	}

}