package com.redhat.rhdm.demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Country implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Country Code")
	private java.lang.String countryCode;
	@org.kie.api.definition.type.Label(value = "Geographic Region")
	private java.lang.String region;

	public Country() {
	}

	public java.lang.String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(java.lang.String countryCode) {
		this.countryCode = countryCode;
	}

	public java.lang.String getRegion() {
		return this.region;
	}

	public void setRegion(java.lang.String region) {
		this.region = region;
	}

	public Country(java.lang.String countryCode, java.lang.String region) {
		this.countryCode = countryCode;
		this.region = region;
	}

}
