package com.redhat.rhdm.demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Order ID")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("Date")
	private java.util.Date date;
	@org.kie.api.definition.type.Label("Order Lines")
	private java.util.List<com.redhat.rhdm.demo.OrderLine> orderlines;

	@org.kie.api.definition.type.Label("SpecialHandling")
	private java.lang.Boolean isSpecial;

	public Order() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.util.Date getDate() {
		return this.date;
	}

	public void setDate(java.util.Date date) {
		this.date = date;
	}

	public java.util.List<com.redhat.rhdm.demo.OrderLine> getOrderlines() {
		return this.orderlines;
	}

	public void setOrderlines(
			java.util.List<com.redhat.rhdm.demo.OrderLine> orderlines) {
		this.orderlines = orderlines;
	}

	public java.lang.Boolean getIsSpecial() {
		return this.isSpecial;
	}

	public void setIsSpecial(java.lang.Boolean isSpecial) {
		this.isSpecial = isSpecial;
	}

	public Order(java.lang.String id, java.util.Date date,
			java.util.List<com.redhat.rhdm.demo.OrderLine> orderlines,
			java.lang.Boolean isSpecial) {
		this.id = id;
		this.date = date;
		this.orderlines = orderlines;
		this.isSpecial = isSpecial;
	}

}