package com.redhat.rhdm.demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Order ID")
	private java.lang.String id;
	@org.kie.api.definition.type.Label(value = "Customer")
	private com.redhat.rhdm.demo.Customer customer;
	@org.kie.api.definition.type.Label(value = "Date")
	private java.util.Date date;
	@org.kie.api.definition.type.Label(value = "Order Lines")
	private java.util.List<com.redhat.rhdm.demo.OrderLine> orderlines;

	public Order() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public com.redhat.rhdm.demo.Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(com.redhat.rhdm.demo.Customer customer) {
		this.customer = customer;
	}

	public java.util.Date getDate() {
		return this.date;
	}

	public void setDate(java.util.Date date) {
		this.date = date;
	}

	public java.util.List<com.redhat.rhdm.demo.OrderLine> getOrderlines() {
		return this.orderlines;
	}

	public void setOrderlines(
			java.util.List<com.redhat.rhdm.demo.OrderLine> orderlines) {
		this.orderlines = orderlines;
	}

	public Order(java.lang.String id, com.redhat.rhdm.demo.Customer customer,
			java.util.Date date,
			java.util.List<com.redhat.rhdm.demo.OrderLine> orderlines) {
		this.id = id;
		this.customer = customer;
		this.date = date;
		this.orderlines = orderlines;
	}

}